# based on check-release from the r-lib examples
name: Ubuntu test install

on: push

jobs:
  check:
    runs-on: ubuntu-16.04
    env:
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/xenial/latest" 
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
